server:
  port: 9898
  #context-path: /demo
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  devtools:
    restart:
       enabled: true
            #设置重启的目录
            #additional-paths: src/main/java
            #classpath目录下的WEB-INF文件夹内容修改不重启
       exclude: WEB-INF/**
       
       
       
       
       

       
coustomTest:
  role: admin